language: go
go:
- 1.10.x
install:
- go get gopkg.in/alecthomas/gometalinter.v1
- go get github.com/gordonklaus/ineffassign
- go get github.com/jgautheron/goconst/cmd/goconst
- go get github.com/kisielk/errcheck
- go get github.com/golang/lint/golint
- go get github.com/golang/dep/cmd/dep
script:
- gometalinter.v1 --vendor --disable-all --enable=vet --enable=golint --enable=ineffassign
  --enable=goconst --tests ./...
before_deploy:
- go get github.com/goreleaser/goreleaser
deploy:
  skip_cleanup: true
  provider: script
  script: goreleaser
  on:
    tags: true
env:
  global:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDsmwE99enDLhJTlatsLmwEygmpdPRplqtL69MO07vnhgMOrl/1dniuLM8Z4uBNKZ3qNEOlXBKdhhW9fFiAC/HnGbB0t8AjgK7EECfEl1jz2825eCsbCODx9aIyOtEbWbOwxKfGSU/kQ4n6tNgYq0YM33J20m//1RgektRjXByWHUyMZnTzdREauzmAUOmf8dit22UNCMZgFX1JfG7H6skj91LfiS9nBZMUDVWZwRnaqBEcifT93ZZ0RWRQD+mfCKq7wW2H3oIjAdkGpE9yoZlkBsvB0eUIT8K6+atmRYqDKudG1ZK9Z1l1eUgZPSWKCsxeFbNVfcpUBYjZwirZ0yo1iaA04xtsulEbFqRdvrULLE3MUWv3e97CfZtjAdjvDJ7mnRxOnmksxbLxnps+f/Gkku9O1PF24I2EtPtA4QOJZD1zOuF3IN6LvZz2iGNEnOYiKL9XufZ70dEh+M6FQ0JK+qAC5m23/nkKaKgURahCMrpMZYD9zkPMcIXcLB3AgZV9VWrWLA76IzF1gyMDMOykWAb0o9qDKwSCTCD3nCHZh9KRdT9sMuURb+eIG74eZ9zoImblUI0twSikmPCtyeUYMZyk2dfRqyy6cRhV4MKP/tlcy0hfNqODnvF0WVBAcnMIY+kOGpAq/R+LMmDWUtYGomZbGnClq74zDZ1yqDzPSw==
